### ISSUE TITLE
Python suggestions

### ISSUE THREAD

**Issue by PaulieTutu** [lmmentel/awesome-python-chemistry#1]
Hello, Lukasz! I've read your article about Python libraries for chemistry and would like to contribute to your list with my suggestions: ODDT (Open Drug Discovery Toolkit), Molecular Design Toolkit, ChemoPy, ChemSpyPy, smilite, MolMiner, molpher-lib. Check them out! :)

**Comment by lmmentel** [comment]
Thanks for the suggestions. I haven't used any of the packages before so it would be great if you could provide short descriptions and links to the packages as in the main README.md. Maybe consider submitting a pull request with the changes?
