### ISSUE TITLE
Criteria to be on your list

### ISSUE THREAD

**Issue by khoivan88** [lmmentel/awesome-python-chemistry#17]
Hi,

Thank you very much for this curated list! It is really helpful to find out what is available out there!

I recently wrote a couple of scripts and I thought the chemistry Python community might find it useful. I am not sure if they meet the criteria to be on this list but I hope that you might consider them:

- [pka_lookup](https://github.com/khoivan88/pka_lookup): this Python script is designed to lookup pKa value from a local database (~7,300 records) and from Pubchem using: CAS number, SMILES, InChI, InChIKey, IUPAC name. If the record is found on Pubchem but not in the local database, the record will be added into the local database for faster access in the future. This script was stemmed from the needs for organic chemists to look up existing pKa values for chemicals in their inventory
- [find_sds](https://github.com/khoivan88/find_sds): This script is designed to find and download safety data sheet of chemicals using CAS number. It uses multithreading to speed up the download process. Lookup databases include: [ChemBlink](https://www.chemblink.com/), [VWR](https://us.vwr.com/store/search/searchMSDS.jsp), [Fisher Scientific](https://www.fishersci.com/us/en/catalog/search/sdshome.html), [TCI Chemicals](www.tcichemicals.com), [ChemicalSafety](https://chemicalsafety.com/sds-search/), [Fluorochem](http://www.fluorochem.co.uk/).

Thank you very much for your consideration!

Best regards,

Khoi Van

**Comment by lmmentel** [comment]
Hi Khoi Van,

I'm glad you found the list useful! 

As for the list I don't have any specific criteria for entering the list and usually go with what seems useful (however you want to define that). There are some good practices that make the adoption easier for community members and developers such as documentation, examples, installation instructions, etc.

Feel free to turn this into a PR. I leave it up to you if you want to create a separate section for scripts or put it directly between the packages.

Cheers

**Comment by khoivan88** [comment]
Thank you very much!! I might wait a bit longer and also to make a good pip install for these before I make a PR. Thank you very much for this very useful list again!
