### ISSUE TITLE
Consider merge two lists

### ISSUE THREAD

**Issue by hsiaoyi0504** [lmmentel/awesome-python-chemistry#2]
Hi, I am glad that see we have similar thought of curating these.
I have tried creating an awesome-cheminformatics before.
https://github.com/hsiaoyi0504/awesome-cheminformatics
However, I don't have time update this for past few months, but I have few new items want to add now.
Do you think is it possible to merge these two lists ?
We can consider create a new organization or in other forms.
Or perhaps you want to keep the scope of this list in python only.
Feel free to discuss this :)

**Comment by lmmentel** [comment]
Hi, thanks for reaching out! There are some truly awesome items in your list that I've missed and I would gladly integrate them into the this one. I started it to collect python specific tools and I would like to keep it that way. That said I'm open to creating a more general resource going beyond python and collecting tools useful for doing chemistry on a computer. What do you think?

**Comment by hsiaoyi0504** [comment]
I like the idea to collect tools useful for doing chemistry on a computer as well, but I think if there are too many places to place these materials, it will make people confused. At the same time, I think we have similar goal. I would suggest we could create a new github organization, create a new repo and put the merged list there. After this, place a quick link in our old repo which let people know there is an updated list in our new repo and point out that our repos are deprecated (likes what we do in developing a software).
